version: "2"
services:
    node:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        ports:
            - "3000:3000"
        restart: on-failure
        command: bash -c "npm install && node server.js"
